### ISSUE TITLE
Last line of `compute_neon_flux()` returns NULL instead of a data frame, despite assignment in README example

### ISSUE THREAD

**Issue by naupaka** [jmzobitz/NEONSoils#12]
The README example stores the output of the function into an object, which is `NULL`. 

```r
> out_fluxes_jan <- compute_neon_flux(input_file_name = "my-file-2020-06.Rda", out_flux_file_name = "my-file-flux-2020-06.Rda")
> out_fluxes_jan
NULL
```

This could be resolved by either a) removing the assignment in the README example so the output is just stored to a file or b) adding a line to the function definition to `return(out_fluxes)` to pass the data frame back out.

https://github.com/jmzobitz/NEONSoils/blob/acb025cc4bb47803d7cb68eccd4d872378527923/R/compute_neon_flux.R#L204

Happy to submit a PR for either fix depending on your preference.

**Comment by jmzobitz** [comment]
Fixed.  I see my error too.  Thanks!
***********
John M. Zobitz, PhD
Pronouns: He, him, his

Professor of Mathematics and Data Science
Data Science Program Director
Environmental Studies Program
Augsburg University
2211 Riverside Avenue, CB 93
Minneapolis, MN 55454

Hagfors Center 187
P: (612) 330-1068
