### ISSUE TITLE
Sketch out the workflow for the R package

### ISSUE THREAD

**Issue by jmzobitz** [jmzobitz/NEONSoils#3]
Identify the data from NEON

**Comment by naupaka** [comment]
This R package can help check for available names: https://github.com/r-lib/available

**Comment by jmzobitz** [comment]
**Questions I need to address: **
- [ ] What are the user inputs?  What are the user outputs?
- [ ] Identify the data coming in from a given site and the format.
- [ ] How will the data be accessed?  Will the user need to pre download it?
- [ ] What types of functions / scripts are needed in order to process the data?
- [ ] Identify the types of auxiliary packages needed to process the data.

GOAL: make a workflow diagram of the key parts of the package before constructing it.

**Comment by naupaka** [comment]
FYI in addition to [NEON-Utilities](https://github.com/NEONScience/NEON-utilities), there is also now [neonstore](https://github.com/cboettig/neonstore) to help with data provenance issues. Some ongoing work to integrate the two, see [this issue](https://github.com/NEONScience/NEON-utilities/issues/99).

**Comment by jmzobitz** [comment]
Here is a link to the initial notes on the sketch: [LINK](https://drive.google.com/file/d/1eYV_rN7_coNPTRD7SY0r2VPFA5DMEJwU/view?usp=sharing)

**Comment by jmzobitz** [comment]
Finished by 10/23 meeting
